//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

pub mod prelude;

pub mod app_user;
pub mod fish_record;
pub mod sys_permission;
pub mod sys_role;
pub mod sys_role_permission;
pub mod sys_setting;
pub mod sys_user;
pub mod sys_user_role;
