//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

pub use super::app_user::Entity as AppUser;
pub use super::fish_record::Entity as FishRecord;
pub use super::sys_permission::Entity as SysPermission;
pub use super::sys_role::Entity as SysRole;
pub use super::sys_role_permission::Entity as SysRolePermission;
pub use super::sys_setting::Entity as SysSetting;
pub use super::sys_user::Entity as SysUser;
pub use super::sys_user_role::Entity as SysUserRole;
